package com.example.temple_idn;

import java.util.ArrayList;

public class TemplesData {
    public static String[][] templeData = new String[][]{
            {"Candi Borobudur", "Magelang, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-borobudur.jpg", "borobudurnews.com", "Borobudur adalah sebuah candi Buddha yang terletak di Borobudur, Magelang, Jawa Tengah, Indonesia. Candi berbentuk stupa ini didirikan oleh para penganut agama Buddha Mahayana sekitar tahun 800-an Masehi pada masa pemerintahan wangsa Syailendra. Borobudur adalah candi atau kuil Buddha terbesar di dunia, sekaligus salah satu monumen Buddha terbesar di dunia.\n" +
                    "\n" +
                    "Monumen ini terdiri atas enam teras berbentuk bujur sangkar yang di atasnya terdapat tiga pelataran melingkar, pada dindingnya dihiasi dengan 2.672 panel relief dan aslinya terdapat 504 arca Buddha. Borobudur memiliki koleksi relief Buddha terlengkap dan terbanyak di dunia. Stupa utama terbesar teletak di tengah sekaligus memahkotai bangunan ini, dikelilingi oleh tiga barisan melingkar 72 stupa berlubang yang di dalamnya terdapat arca Buddha tengah duduk bersila dalam posisi teratai sempurna dengan mudra (sikap tangan) Dharmachakra mudra (memutar roda dharma). (Sumber: id.wikipedia.org)"},
            {"Candi Prambanan", "Sleman, Daerah Istimewa Yogyakarta", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-prambanan.jpg", "wikipedia.org", "Candi Prambanan atau Candi Roro Jonggrang adalah kompleks candi Hindu terbesar di Indonesia yang dibangun pada abad ke-9 masehi. Candi ini dipersembahkan untuk Trimurti, tiga dewa utama Hindu yaitu Brahma sebagai dewa pencipta, Wishnu sebagai dewa pemelihara, dan Siwa sebagai dewa pemusnah.\n" + "\n" + " Berdasarkan prasasti Siwagrha nama asli kompleks candi ini adalah Siwagrha (bahasa Sanskerta yang bermakna 'Rumah Siwa'), dan memang di garbagriha (ruang utama) candi ini bersemayam arca Siwa Mahadewa setinggi tiga meter yang menujukkan bahwa di candi ini dewa Siwa lebih diutamakan. (Sumber: id.wikipedia.org)"},
            {"Candi Sewu", "Klaten, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-sewu.jpg", "wikipedia.org", "Candi Sewu atau Manjusrighra adalah candi Buddha yang dibangun pada abad ke-8 Masehi yang berjarak hanya delapan ratus meter di sebelah utara Candi Prambanan. Candi Sewu merupakan kompleks candi Buddha terbesar kedua setelah Candi Borobudur di Jawa Tengah. Candi Sewu berusia lebih tua daripada Candi Borobudur dan Prambanan. Meskipun aslinya memiliki 249 candi, oleh masyarakat setempat candi ini dinamakan \"Sewu\" yang berarti seribu dalam bahasa Jawa. Penamaan ini berdasarkan kisah legenda Loro Jonggrang.\n" +
                    "\n" +
                    "Secara administratif, kompleks Candi Sewu terletak di Dukuh Bener, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Provinsi Jawa Tengah. (Sumber: id.wikipedia.org)"},
            {"Candi Mendut", "Magelang, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-mendut.jpg", "wikipedia.org", "Candi Mendut adalah sebuah candi bercorak Buddha. Candi yang terletak di Jalan Mayor Kusen Kota Mungkid, Kabupaten Magelang, Jawa Tengah ini, letaknya berada sekitar 3 kilometer dari Candi Borobudur. Candi Mendut didirikan semasa pemerintahan Raja Indra dari dinasti Syailendra. Di dalam prasasti Karangtengah yang bertarikh 824 Masehi, disebutkan bahwa raja Indra telah membangun bangunan suci bernama wenuwana yang artinya adalah hutan bambu. Oleh seorang ahli arkeologi Belanda bernama J.G. de Casparis, kata ini dihubungkan dengan Candi Mendut. (Sumber: id.wikipedia.org)"},
            {"Candi Dieng", "Wonosobo, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-dieng.jpg", "losmenbudjono.com", "Candi Dieng adalah kelompok kompleks candi Hindu abad ke-7 terletak di Dataran Tinggi Dieng, dekat Wonosobo, Jawa Tengah, Indonesia. Bangunan-bangunan ini berasal dari Kerajaan Kalingga. Dataran tinggi ini adalah tempat berdirinya delapan candi Hindu kecil yang merupakan salah satu bangunan keagamaan tertua yang masih bertahan yang pernah dibangun di Jawa.\n" + "\n" + "Nama sebenarnya dari candi tersebut, sejarah, dan raja yang bertanggung jawab atas pembangunan candi-candi ini tidak diketahui. Hal ini karena kelangkaan data dan prasasti yang terkait dengan pembangunan candi-candi ini. Penduduk Jawa lokal menamakan setiap candi sesuai dengan tokoh wayang Jawa, kebanyakan diambil dari epos Mahabharata. (Sumber: id.wikipedia.org)"},
            {"Candi Ratu Boko", "Sleman, Daerah Istimewa Yogyakarta", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-ratuboko.jpg", "traveloka.com", "Situs Ratu Baka atau Candi Boko adalah situs purbakala yang merupakan kompleks sejumlah sisa bangunan yang berada kira-kira 3 km di sebelah selatan dari kompleks Candi Prambanan, 18 km sebelah timur Kota Yogyakarta atau 50 km barat daya Kota Surakarta, Jawa Tengah, Indonesia. Situs Ratu Boko terletak di sebuah bukit pada ketinggian 196 meter dari permukaan laut. Luas keseluruhan kompleks adalah sekitar 25 ha.\n" +
                    "\n" +
                    "Situs ini menampilkan atribut sebagai tempat berkegiatan atau situs permukiman, namun fungsi tepatnya belum diketahui dengan jelas. Ratu Boko diperkirakan sudah dipergunakan orang pada abad ke-8 pada masa Wangsa Sailendra (Rakai Panangkaran) dari Kerajaan Medang (Mataram Hindu). Dilihat dari pola peletakan sisa-sisa bangunan, diduga kuat situs ini merupakan bekas keraton (istana raja). Pendapat ini berdasarkan pada kenyataan bahwa kompleks ini bukan candi atau bangunan dengan sifat religius, melainkan sebuah istana berbenteng dengan bukti adanya sisa dinding benteng dan parit kering sebagai struktur pertahanan. Sisa-sisa permukiman penduduk juga ditemukan di sekitar lokasi situs ini.\n" +
                    "\n" +
                    "Nama \"Ratu Boko\" berasal dari legenda masyarakat setempat. Ratu Boko (bahasa Jawa, arti harafiah: \"raja bangau\") adalah ayah dari Loro Jonggrang, yang juga menjadi nama candi utama pada kompleks Candi Prambanan. Kompleks bangunan ini dikaitkan dengan legenda rakyat setempat Loro Jonggrang. (Sumber: id.wikipedia.org)"},
            {"Candi Gedong Songo", "Semarang, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-gedongsongo.jpg", "wikipedia.org", "Candi Gedong Songo adalah nama sebuah komplek bangunan candi peninggalan budaya Hindu yang terletak di desa Candi, Kecamatan Bandungan, Kabupaten Semarang, Jawa Tengah, Indonesia. Tepatnya di lereng Gunung Ungaran. Di kompleks candi ini terdapat sembilan buah candi.\n" +
                    "\n" +
                    "Candi ini diketemukan oleh Raffles pada tahun 1804 dan merupakan peninggalan budaya Hindu dari zaman Wangsa Syailendra abad ke-9 (tahun 927 masehi).\n" +
                    "\n" +
                    "Candi ini memiliki persamaan dengan kompleks Candi Dieng di Wonosobo. Candi ini terletak pada ketinggian sekitar 1.200 m di atas permukaan laut sehingga suhu udara disini cukup dingin (berkisar antara 19-27 °C).\n" +
                    "\n" +
                    "Lokasi sembilan candi yang tersebar di lereng Gunung Ungaran ini memiliki pemandangan alam yang indah. Selain itu, objek wisata ini juga dilengkapi dengan pemandian air panas dari mata air yang mengandung belerang, area perkemahan, dan wisata berkuda. (Sumber: id.wikipedia.org)"},
            {"Candi Ijo", "Sleman, Daerah Istimewa Yogyakarta", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-ijo.jpg", "wikipedia.org", "Candi Ijo adalah sebuah kompleks percandian bercorak Hindu, berada 4 kilometer arah tenggara dari Candi Ratu Boko atau kira-kira 18 kilometer di sebelah timur kota Yogyakarta.\n" + "\n" + "Candi ini diperkirakan dibangun antara kurun abad ke-10 sampai dengan ke-11 Masehi pada saat zaman Kerajaan Medang periode Mataram. (Sumber: id.wikipedia.org)"},
            {"Candi Sambisari", "Sleman, Daerah Istimewa Yogyakarta", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-sambisari.jpg", "wikipedia.org", "Candi Sambisari adalah candi Hindu (Siwa) yang berada di Purwomartani, Kalasan, Sleman, Yogyakarta, kira-kira 12 km di sebelah timur kota Yogyakarta ke arah kota Solo atau kira-kira 4 km sebelum kompleks Candi Prambanan.\n" +"\n"+ "Candi ini dibangun pada abad ke-9 pada masa pemerintahan raja Rakai Garung pada zaman Kerajaan Mataram Kuno. (Sumber: id.wikipedia.org)"},
            {"Candi Tikus", "Mojokerto, Jawa Timur", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-tikus.jpg", "wikipedia.org", "Candi Tikus adalah sebuah peninggalan purbakala yang terletak di dukuh Dinuk, Desa Temon, Kecamatan Trowulan, Kabupaten Mojokerto, Jawa Timur. \n" +
                    "Candi Tikus yang semula telah terkubur dalam tanah ditemukan kembali pada tahun 1914. Penggalian situs dilakukan berdasarkan laporan bupati Mojokerto, R.A.A. Kromojoyo Adinegoro, tentang ditemukannya miniatur candi di sebuah pekuburan rakyat. Pemugaran secara menyeluruh dilakukan pada tahun 1984 sampai dengan 1985.\n" +"\n"+ "Nama ‘Tikus’ hanya merupakan sebutan yang digunakan masyarakat setempat. Konon, pada saat ditemukan, tempat candi tersebut berada merupakan sarang tikus. Belum didapatkan sumber informasi tertulis yang menerangkan secara jelas tentang kapan, untuk apa, dan oleh siapa Candi Tikus dibangun. Akan tetapi dengan adanya miniatur menara diperkirakan candi ini dibangun antara abad ke-13 sampai ke-14 M, karena miniatur menara merupakan ciri arsitektur pada masa itu. (Sumber: id.wikipedia.org)"},
            {"Candi Plaosan", "Klaten, Jawa Tengah", "https://raw.githubusercontent.com/danielprasaja/TempleList-dicoding-AP/master/img-temples/candi-plaosan.jpg", "wikipedia.org", "Candi Plaosan adalah sebutan untuk kompleks percandian yang terletak di Dukuh Plaosan, Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, Provinsi Jawa Tengah, Indonesia. Candi ini terletak kira-kira satu kilometer ke arah timur-laut dari Candi Sewu atau Candi Prambanan. Adanya kemuncak stupa, arca Buddha, serta candi-candi perwara (pendamping/kecil) yang berbentuk stupa menandakan bahwa candi-candi tersebut adalah candi Buddha. Kompleks ini dibangun pada abad ke-9 oleh Raja Rakai Pikatan dan Sri Kahulunan pada zaman Kerajaan Medang, atau juga dikenal dengan nama Kerajaan Mataram Kuno.\n" +
                    "\n" +
                    "Kompleks Candi Plaosan terdiri atas Candi Plaosan Lor dan Candi Plaosan Kidul. Pada masa lalu, Kompleks percandian ini dikelilingi oleh parit berbentuk persegi panjang. Sisa struktur tersebut masih bisa dilihat sampai saat ini di bagian timur dan barat candi. (Sumber: id.wikipedia.org)"}
    };

    public static ArrayList<Temple> getListData(){
        ArrayList<Temple> list = new ArrayList<>();
        for (String[] data : templeData){
            Temple temple = new Temple();
            temple.setName(data[0]);
            temple.setLocation(data[1]);
            temple.setImage(data[2]);
            temple.setSource_img(data[3]);
            temple.setDtl_info(data[4]);
            list.add(temple);
        }
        return list;
    }
}
